services:
  db:
    image: postgres:16-alpine
    container_name: geocms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: geocms
      POSTGRES_PASSWORD: geocms
      POSTGRES_DB: geocms
    volumes:
      - geocms_pg_data:/var/lib/postgresql/data

volumes:
  geocms_pg_data:
